---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  namespace: myns
  labels:
    app: dov
type: Opaque
data:
  INSTANCE_NAME: c2VjcmV0IHZhbHVl
  DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dov-deploy
  namespace: myns
  labels: 
    app: dov
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dov
      dept: eng
  template:
    metadata: 
      name: dov-po
      labels: 
        app: dov
        dept: eng
    spec:
      containers:
        - name: dov-container
          image: chukmunnlee/dov-bear:v5
          imagePullPolicy: IfNotPresent
          env: 
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          envFrom:
          - secretRef:
              name: dov-secret
          ports:
          - name: dov-port
            containerPort: 3000
          livenessProbe:
            httpGet: 
              path: /healthz
              port: 3000
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
spec:
  type: NodePort
  selector: 
    app: dov
    dept: eng
  ports: 
  - port: 8080
    targetPort: dov-port
    

